### ISSUE TITLE
Github?

### ISSUE THREAD

**Issue by sargun** [pcmacdon/jsish#1]
Is the home of this project ever going to be Github, or always sourceforge?

**Comment by pcmacdon** [comment]
Thanks for inquiring, but the answer is neither.  The jsish home has
recently moved to jsish.orr where it is hosted in a fossil repository.

However fossil does support git export so, we're looking at setting that up
to happen automatically..

Peter

**Comment by pcmacdon** [comment]
FYI, git sync is now setup, to coincide with the 3.0 release of Jsi.
